name: training_camp_scheduling
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  custom_lint:
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1
  riverpod_lint: ^2.3.2
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
      - asset: assets/fonts/NotoSansJP/NotoSansJP-thin.ttf
        weight: 100
      - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSansJP/NotoSansJP-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/NotoSansJP/NotoSansJP-Black.ttf
        weight: 900


flutter_icons: 
  image_path_android: assets/launcher_icon/android_icon.png
  adaptive_icon_background: '#FFFFFF' #iconの背景色
  adaptive_icon_foreground: assets/launcher_icon/android_icon.png
  image_path_ios: assets/launcher_icon/ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 30 #Androidの最小SDKバージョン
  ios: true  