name: training_camp_scheduling
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  custom_lint:
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true


flutter_icons: 
  image_path_android: assets/launcher_icon/android_icon.png
  adaptive_icon_background: '#FFFFFF' #iconの背景色
  adaptive_icon_foreground: assets/launcher_icon/android_icon.png
  image_path_ios: assets/launcher_icon/ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 30 #Androidの最小SDKバージョン
  ios: true  